// <auto-generated />
using System;
using tallermecanico.infretruture.DBContex;
using tallermecanico.infretruture.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tallermecanico.infretruture.Migrations;

[DbContext(typeof(CrudAPIContex))]
[Migration("20251031013510_AddNewColumnToCustomers")]
partial class AddNewColumnToCustomers
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("CustomerId");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Customers");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Invoice", b =>
            {
                b.Property<int>("InvoiceId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<int>("SellerId")
                    .HasColumnType("int");

                b.HasKey("InvoiceId");

                b.HasIndex("CustomerId");

                b.HasIndex("SellerId");

                b.ToTable("Invoices");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Mechanic", b =>
            {
                b.Property<int>("MechanicId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Specialty")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("MechanicId");

                b.ToTable("Mechanics");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Repair", b =>
            {
                b.Property<int>("RepairId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairId"));

                b.Property<double>("Cost")
                    .HasColumnType("float");

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("InvoiceId")
                    .HasColumnType("int");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MechanicId")
                    .HasColumnType("int");

                b.Property<int?>("SellerId")
                    .HasColumnType("int");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("RepairId");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceId");

                b.HasIndex("MechanicId");

                b.HasIndex("SellerId");

                b.HasIndex("VehicleId");

                b.ToTable("Repairs");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Sale", b =>
            {
                b.Property<int>("SaleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<int?>("InvoiceId")
                    .HasColumnType("int");

                b.Property<int>("SellerId")
                    .HasColumnType("int");

                b.Property<double>("Total")
                    .HasColumnType("float");

                b.HasKey("SaleId");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceId");

                b.HasIndex("SellerId");

                b.ToTable("Sales");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.SaleDetail", b =>
            {
                b.Property<int>("SaleDetailId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDetailId"));

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<int>("SaleId")
                    .HasColumnType("int");

                b.Property<int>("SparePartId")
                    .HasColumnType("int");

                b.Property<double>("UnitPrice")
                    .HasColumnType("float");

                b.HasKey("SaleDetailId");

                b.HasIndex("SaleId");

                b.HasIndex("SparePartId");

                b.ToTable("SaleDetails");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Seller", b =>
            {
                b.Property<int>("SellerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("SellerId");

                b.ToTable("Sellers");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.SparePart", b =>
            {
                b.Property<int>("SparePartId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartId"));

                b.Property<int?>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("EntryDate")
                    .HasColumnType("datetime2");

                b.Property<int>("InitialQuantity")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<int?>("SellerId")
                    .HasColumnType("int");

                b.Property<double>("UnitPrice")
                    .HasColumnType("float");

                b.Property<double>("WholesalePrice")
                    .HasColumnType("float");

                b.HasKey("SparePartId");

                b.HasIndex("CustomerId");

                b.HasIndex("SellerId");

                b.ToTable("SpareParts");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Vehicle", b =>
            {
                b.Property<int>("VehicleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Color")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<int?>("InvoiceId")
                    .HasColumnType("int");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("SellerId")
                    .HasColumnType("int");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.HasKey("VehicleId");

                b.HasIndex("CustomerId");

                b.HasIndex("InvoiceId");

                b.HasIndex("SellerId");

                b.ToTable("Vehicles");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Invoice", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Customer", "Customer")
                    .WithMany("Invoices")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.Seller", "Seller")
                    .WithMany("Invoices")
                    .HasForeignKey("SellerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");

                b.Navigation("Seller");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Repair", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Customer", "Customer")
                    .WithMany("Repairs")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.Invoice", "Invoice")
                    .WithMany("Repairs")
                    .HasForeignKey("InvoiceId");

                b.HasOne("tallermecanico.domain.Models.Entityes.Mechanic", "Mechanic")
                    .WithMany("Repairs")
                    .HasForeignKey("MechanicId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.Seller", null)
                    .WithMany("Repairs")
                    .HasForeignKey("SellerId");

                b.HasOne("tallermecanico.domain.Models.Entityes.Vehicle", "Vehicle")
                    .WithMany("Repairs")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");

                b.Navigation("Invoice");

                b.Navigation("Mechanic");

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Sale", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Customer", "Customer")
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.Invoice", null)
                    .WithMany("Sales")
                    .HasForeignKey("InvoiceId");

                b.HasOne("tallermecanico.domain.Models.Entityes.Seller", "Seller")
                    .WithMany()
                    .HasForeignKey("SellerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");

                b.Navigation("Seller");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.SaleDetail", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Sale", "Sale")
                    .WithMany("SaleDetails")
                    .HasForeignKey("SaleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.SparePart", "SparePart")
                    .WithMany("SaleDetails")
                    .HasForeignKey("SparePartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Sale");

                b.Navigation("SparePart");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.SparePart", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Customer", null)
                    .WithMany("SpareParts")
                    .HasForeignKey("CustomerId");

                b.HasOne("tallermecanico.domain.Models.Entityes.Seller", null)
                    .WithMany("SpareParts")
                    .HasForeignKey("SellerId");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Vehicle", b =>
            {
                b.HasOne("tallermecanico.domain.Models.Entityes.Customer", "Customer")
                    .WithMany("Vehicles")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("tallermecanico.domain.Models.Entityes.Invoice", "Invoice")
                    .WithMany("Vehicles")
                    .HasForeignKey("InvoiceId");

                b.HasOne("tallermecanico.domain.Models.Entityes.Seller", "Seller")
                    .WithMany("Vehicles")
                    .HasForeignKey("SellerId");

                b.Navigation("Customer");

                b.Navigation("Invoice");

                b.Navigation("Seller");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Customer", b =>
            {
                b.Navigation("Invoices");

                b.Navigation("Repairs");

                b.Navigation("SpareParts");

                b.Navigation("Vehicles");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Invoice", b =>
            {
                b.Navigation("Repairs");

                b.Navigation("Sales");

                b.Navigation("Vehicles");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Mechanic", b =>
            {
                b.Navigation("Repairs");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Sale", b =>
            {
                b.Navigation("SaleDetails");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Seller", b =>
            {
                b.Navigation("Invoices");

                b.Navigation("Repairs");

                b.Navigation("SpareParts");

                b.Navigation("Vehicles");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.SparePart", b =>
            {
                b.Navigation("SaleDetails");
            });

        modelBuilder.Entity("tallermecanico.domain.Models.Entityes.Vehicle", b =>
            {
                b.Navigation("Repairs");
            });
#pragma warning restore 612, 618
    }
}
