// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tallermecanico.infretruture.DBContex;

#nullable disable

namespace tallermecanico.infretruture.Migrations
{
    [DbContext(typeof(CrudAPIContex))]
    partial class CrudAPIContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tallermecanico.infretruture.Model.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.InvoiceModel", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SellerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.MechanicModel", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MechanicId");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.RepairModel", b =>
                {
                    b.Property<int>("RepairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("SellerModelSellerId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("RepairId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("SellerModelSellerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SaleDetailModel", b =>
                {
                    b.Property<int>("SaleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDetailId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("SaleDetailId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SparePartId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SaleModel", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceModelInvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceModelInvoiceId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SellerModel", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SparePartModel", b =>
                {
                    b.Property<int>("SparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SparePartId"));

                    b.Property<int?>("CustomerModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SellerModelSellerId")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<double>("WholesalePrice")
                        .HasColumnType("float");

                    b.HasKey("SparePartId");

                    b.HasIndex("CustomerModelId");

                    b.HasIndex("SellerModelSellerId");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.VehicleModel", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SellerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.InvoiceModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.CustomerModel", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.SellerModel", "Seller")
                        .WithMany("Invoices")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.RepairModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.CustomerModel", "Customer")
                        .WithMany("Repairs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.InvoiceModel", "Invoice")
                        .WithMany("Repairs")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("tallermecanico.infretruture.Model.MechanicModel", "Mechanic")
                        .WithMany("Repairs")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.SellerModel", null)
                        .WithMany("Repairs")
                        .HasForeignKey("SellerModelSellerId");

                    b.HasOne("tallermecanico.infretruture.Model.VehicleModel", "Vehicle")
                        .WithMany("Repairs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SaleDetailModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.SaleModel", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.SparePartModel", "SparePart")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SaleModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.InvoiceModel", null)
                        .WithMany("Sales")
                        .HasForeignKey("InvoiceModelInvoiceId");

                    b.HasOne("tallermecanico.infretruture.Model.SellerModel", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SparePartModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.CustomerModel", null)
                        .WithMany("SpareParts")
                        .HasForeignKey("CustomerModelId");

                    b.HasOne("tallermecanico.infretruture.Model.SellerModel", null)
                        .WithMany("SpareParts")
                        .HasForeignKey("SellerModelSellerId");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.VehicleModel", b =>
                {
                    b.HasOne("tallermecanico.infretruture.Model.CustomerModel", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallermecanico.infretruture.Model.InvoiceModel", "Invoice")
                        .WithMany("Vehicles")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("tallermecanico.infretruture.Model.SellerModel", "Seller")
                        .WithMany("Vehicles")
                        .HasForeignKey("SellerId");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.CustomerModel", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Repairs");

                    b.Navigation("SpareParts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.InvoiceModel", b =>
                {
                    b.Navigation("Repairs");

                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.MechanicModel", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SaleModel", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SellerModel", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Repairs");

                    b.Navigation("SpareParts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.SparePartModel", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("tallermecanico.infretruture.Model.VehicleModel", b =>
                {
                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
